--- 
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: gophish-pv
  labels:
    type: local
spec: 
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: gophish-pvc
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
