apiVersion: v1
kind: Pod
metadata:
  name: gophish
  labels: 
    app.kubernetes.io/name: gophish
spec:
  initContainers:
  - name: volume-dirs-init-cntr
    image: busybox:1.36
    command:
    - "/bin/mkdir"
    args:
    - "-p"
    - "/security/gophish"
    volumeMounts:
    - mountPath: /security
      name: security-data
  containers:
  - name: gophish
    image: docker.io/heywoodlh/gophish:0.12.0
    ports:
    - containerPort: 80
    - containerPort: 3333
    env: 
      - name: ADMIN_CERT_PATH
        value: "/security/gophish/gophish.crt"
      - name: ADMIN_CERT_PATH
        value: "/security/gophish/gophish.key"
      - name: DB_FILE_PATH
        value: "/security/gophish/gophish.db"
      - name: PHISH_LISTEN_URL
        value: "0.0.0.0:80"
    volumeMounts: 
    - mountPath: /security
      name: security-data
  volumes: 
    - 
      name: security-data
      persistentVolumeClaim: 
        claimName: security-pvc
  imagePullPolicy: Always
