apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gophish
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  project: security
  source:
    path: kustomize/gophish/overlays/main
    repoURL: https://github.com/heywoodlh/k8s-security
    targetRevision: HEAD
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
