apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kali-rdp
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: security
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  project: security
  source:
    path: kustomize/kali-rdp/overlays/main
    repoURL: https://github.com/heywoodlh/k8s-security
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
