apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kali-rdp
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  project: default
  source:
    path: kustomize/kali-rdp/overlays/main
    repoURL: https://github.com/heywoodlh/k8s-security
    targetRevision: {{ .Values.version }}
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
