apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-secret-generator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: security
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  project: security
  source:
    path: charts/kubernetes-secret-generator
    repoURL: https://github.com/heywoodlh/k8s-security
    targetRevision: HEAD
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
