apiVersion: v1
kind: Pod
metadata:
  name: kali-rdp
  labels: 
    app.kubernetes.io/name: kali-rdp
spec:
  containers:
  - name: rdp-kali-linux
    image: docker.io/heywoodlh/rdp-kali-linux-full:2022.4
    ports:
    - containerPort: 3389
    - containerPort: 22
