apiVersion: v1
kind: Service
metadata:
  name: kali-rdp
spec:
  selector:
    app.kubernetes.io/name: kali-rdp
  ports:
    - protocol: TCP
      port: 3389
      targetPort: 3389
      name: rdp
    - protocol: TCP
      port: 22
      targetPort: 22
      name: ssh
