apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
helmCharts:
- name: kubernetes-secret-generator
  includeCRDs: true
  valuesInline:
    image:
      registry: quay.io
      repository: mittwald/kubernetes-secret-generator
      tag: v3.4.0
    watchNamespace: ""
  releaseName: kubernetes-secret-generator
  version: 3.4.0
  repo: https://helm.mittwald.de 
